# Generated by Django 3.2.5 on 2021-07-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0002_graphinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Pdf', models.FileField(upload_to='uploadmyfile/pdfs/')),
            ],
        ),
    ]
