# Generated by Django 3.2.5 on 2021-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0003_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphinput',
            name='Value1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='graphinput',
            table='WebApplication_graphinput',
        ),
    ]
